#!/usr/bin/env bash
#
# Build the hkjn/node Docker images.
#
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="node"
ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"

declare -A BASEIMAGES
BASEIMAGES[x86_64]=hkjn/alpine:x86_64
BASEIMAGES[armv7l]=hkjn/alpine:armv7l
BASEIMAGE=${BASEIMAGES[$ARCH]}

TAG="$DOCKER_USER/$DOCKER_IMAGE:$ARCH"

echo "Building $TAG in $BUILD_DIR.."
sed "s|ARG_FROM|${BASEIMAGE}|g" Dockerfile.in > $BUILD_DIR/Dockerfile
docker build -t $TAG $BUILD_DIR
NO_PUSH=${NO_PUSH:-""}
if [[ ! "$NO_PUSH" ]]; then
  docker push $TAG
fi
